### ISSUE TITLE
composer require doesn't work

### ISSUE THREAD

**Issue by lasergoat** [BaglerIT/OAuthSimple#2]
Hi! Thanks for making this. It looks awesome, however I cannot actually `composer require` it.

```composer require baglerit/oauthsimple``` doesn't find the project.

I can manually include it for now.

**ERROR**
```
[InvalidArgumentException]                                                   
  Could not find package baglerit/oauthsimple at any version for your minimum  
  -stability (stable). Check the package spelling or your minimum-stability  
```

**Comment by kloor** [comment]
Unfortunately, no releases of this package have been tagged. Until they are, you'll have to specify the dev-master version:

`composer require baglerit/oauthsimple:dev-master`

You may also need to add `"minimum-stability": "dev"` to your composer.json, depending on how your package is used.
